# Tensor

In [2]:
import tensorflow as tf
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

c = tf.constant(1)
v = tf.Variable(1)
print(c)
print(v)

tf.Tensor(1, shape=(), dtype=int32)
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>


In [5]:
x = tf.constant(4)
print(x)
print("{} Tensor".format(x.ndim))

tf.Tensor(4, shape=(), dtype=int32)
0 Tensor


In [6]:
x = tf.constant([1, 2, 3, 4, 5, 6])
print(x)
print("{} Tensor".format(x.ndim))

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)
1 Tensor


In [7]:
x = tf.constant([[1, 2, 3], [4, 5, 6]])
print(x)
print("{} Tensor".format(x.ndim))

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
2 Tensor


# TensorFlow Basic calculation

In [10]:
import numpy as np

print('Eager Execution: {}'.format(tf.executing_eagerly()))

Eager Execution: True


In [11]:
a = tf.constant(3)
b = tf.constant(4)

print('a = {}'.format(a))
print('b = {}'.format(b))

a = 3
b = 4


In [12]:
print(a)
print(b)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


In [13]:
c = a + b
print(c)
d = a * b
print(d)

tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)


In [14]:
a = tf.constant([[1., 2.], [3., 4.]], dtype=tf.float32)
b = np.array([[1., 0], [2., 3.]], dtype=np.float32)
print('a constant: {}D Tensor'.format(a.ndim))

a constant: 2D Tensor


In [15]:
print(a)
print(b)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
[[1. 0.]
 [2. 3.]]


In [16]:
c = a + b

In [17]:
print(c)

tf.Tensor(
[[2. 2.]
 [5. 7.]], shape=(2, 2), dtype=float32)


In [18]:
d = tf.matmul(a, b)

In [19]:
print(d)

tf.Tensor(
[[ 5.  6.]
 [11. 12.]], shape=(2, 2), dtype=float32)


In [20]:
print('NumpyArray:\n {}'.format(c.numpy()))

NumpyArray:
 [[2. 2.]
 [5. 7.]]


In [22]:
w = tf.Variable([[1.0]])

with tf.GradientTape() as tape:
    loss = w * w
    
grad = tape.gradient(loss, w)
print(grad)

tf.Tensor([[2.]], shape=(1, 1), dtype=float32)
